ARG PHP_TARGET=7.4-apache

# Install base environment
FROM php:$PHP_TARGET as base
RUN apt-get update
RUN apt-get install -y wget zip unzip zlib1g-dev libzip-dev libpng-dev vim git
RUN docker-php-ext-install -j$(nproc) mysqli pdo_mysql gd zip pcntl exif

# Configure PHP with local options
ENV PHP_INI_DIR /usr/local/etc/php
COPY ./php_config/local.ini $PHP_INI_DIR/conf.d/

# Enable common Apache modules
RUN a2enmod headers expires rewrite

# Link local dotfiles
RUN ln -s /var/www/dotfiles/.bash_profile ~/.bash_profile
RUN ln -s /var/www/dotfiles/.bash_prompt_docker ~/.bash_prompt
RUN ln -s /var/www/dotfiles/.git_completion.bash ~/.git_completion.bash
RUN ln -s /var/www/dotfiles/.git_prompt.sh ~/.git_prompt.sh
RUN ln -s /var/www/dotfiles/.gitconfig ~/.gitconfig
RUN ln -s /var/www/dotfiles/.gitignore_global ~/.gitignore_global
RUN echo 'source ~/.bash_profile' >> ~/.bashrc

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Set working directory to workspace
WORKDIR /var/www
