# PHP + Apache
FROM php:8.1-apache

# Update OS and install common dev tools
RUN apt-get update
RUN apt-get install -y wget vim git zip unzip zlib1g-dev libzip-dev libpng-dev libicu-dev

# Install PHP extensions needed
RUN docker-php-ext-install -j$(nproc) mysqli pdo_mysql gd zip pcntl exif intl bcmath

# Enable common Apache modules
RUN a2enmod headers expires rewrite

# Link local dotfiles for consistent CLI (optional)
RUN ln -s /var/www/dotfiles/.bash_profile ~/.bash_profile
RUN ln -s /var/www/dotfiles/.bash_prompt_docker ~/.bash_prompt
RUN ln -s /var/www/dotfiles/.git_completion.bash ~/.git_completion.bash
RUN ln -s /var/www/dotfiles/.git_prompt.sh ~/.git_prompt.sh
RUN ln -s /var/www/dotfiles/.gitconfig ~/.gitconfig
RUN ln -s /var/www/dotfiles/.gitignore_global ~/.gitignore_global
RUN echo 'source ~/.bash_profile' >> ~/.bashrc

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

RUN composer global require friendsofphp/php-cs-fixer

# Set working directory to web files
WORKDIR /var/www
